
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Copy LICENSE.txt to dist
      run: cp LICENSE src/dist/windows/LICENSE.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: steam-store-checker
        path: src/dist/windows

    - name: GitHub Release
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "src/dist/windows/*.exe"
        draft: false
        tags: true
