
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: src

    - name: Copy LICENSE.txt to dist
      run: cp LICENSE src/dist/windows/LICENSE.txt

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: steam-store-checker
        path: src/dist/windows
